### PR TITLE
Enable IceGrid/replication test

### PR DESCRIPTION
**Pull request by pepone**
I wonder if this was failing due to an IceStorm bug fixed in https://github.com/zeroc-ice/ice/commit/ba75c749a2e37821306eb3c9f5262cda5fdf66b6

### CODE REVIEW

**Review by externl — APPROVED** [review]

**Comment by externl** [comment]
I think so! Sorry, I introduced a merged conflict by filtering out a different test.

**Comment by pepone** [comment]
> I introduced a merged conflict by filtering out a different test.

No worries, I just wanted to check if the test worked with CI after the IceStorm updates.

**Comment by pepone** [comment]
still failing on Windows

```
2024-03-07T21:16:12.1082188Z testing node session establishment... failed!
2024-03-07T21:16:12.1099315Z D:\a\ice\ice\cpp\test\IceGrid\replication\AllTests.cpp:845: assertion `slave1Admin->pingNode("Node1")' failed
```

**Comment by externl** [comment]
any idea what the issue could be?

**Pull request closed without merging**
