### PR TITLE
Stop ignoring errors when IceSSl.VerifyPeer is set to 0

### PR DESCRIPTION
**Pull request by pepone**
This small PR changes the behavior of `IceSSL.VerifyPeer` 0,  certificate validation errors will no longer be ignored. The property is still useful in a server context to not request a client certificate.  .NET always requires a server certificate so it is no longer useful to set this in a client.

### CODE REVIEW

**Comment by externl** [comment]
Maybe setting `IceSSL.VerifyPeer=0` should be a configuration error. Only support `1` or `2`.

**Comment by pepone** [comment]
> Maybe setting `IceSSL.VerifyPeer=0` should be a configuration error. Only support `1` or `2`.

0 in a server means to not require a client certificate, are you suggesting to always require the client certificate?

**Comment by externl** [comment]
Right, that's still a useful server side configuration. 

This PR now kinda changes the meaning of `0` to be the same as `1` or outgoing connections.

**Comment by pepone** [comment]
Well for outgoing this property now does nothing as show in your table, is only relevant for incoming, there is also your concern of making 1 and 2 equivalent for incoming, but I undecided about this.

**Comment by externl** [comment]
I kinda like the current way, which make's it a server side only property really.

**Pull request merged**
