### PR TITLE
Add RefreshEndpoints retry policy

### PR DESCRIPTION
**Pull request by pepone**
This PR adds a new retry policy `RefreshEndpoints` that indicates the client should refresh endpoints after retrying using a different replica. For direct proxies, it is the same as OtherReplica for indirect proxies the client will clear the locator cache so that a new endpoint lookup is performed, the connector associated with the failure is excluded for the current retry sequence.

ONE and OpNE throw by Ice run-time have been updated to use this new policy.

### CODE REVIEW

**Comment by externl** [comment]
I'm not really convinced it's the responsibility of the OA to tell a client to refresh it's endpoints if it doesn't have an object.

**Comment by pepone** [comment]
I think we have to make some assumptions, 

OtherReplica suggests you try another replica because this one cannot handle the request, the client might not know about other replicas and it would fail.

RefreshEndpoints suggests that you might be using an outdated endpoint, the server or client cannot truly know if the object is really gone, or the client is using an outdated endpoint, but it is a suggestion that the client using an indirect endpoint might want to refresh endpoints and try again.

**Comment by bernardnormier** [comment]
What is the use-case for RefreshEndpoints and say OperationNotExistException?

A client sends a request using an indirect proxy with cached endpoints - so one cached endpoint - and gets OperationNotExistException. It could be because the cached endpoints are out of date and the new server that implements this operation is now registered with the Locator and available, while the old server is gone?

When would an application pick RetryPolicy = RefreshEndpoints when throwing an exception? When it expects there is a newer version of itself running that can handle the request? E.g.:
```
    // Maybe there is a newer version that implements this operation, and the client reached me through a stale endpoint
    throw new NoImplementException("this operation is not implemented yet", retryPolicy: RefreshEndpoints);
```

Overall, I think it's such a narrow use-case that nobody would ever specify this retry policy. It also makes the server worry about the client's locator cache (the stale endpoints), which is not an obvious server concern.

So does it make sense to add it at all? Is there a better solution to this use-case?

**Comment by pepone** [comment]
> So does it make sense to add it at all? Is there a better solution to this use-case?

A simpler way might be to always clear the cache after an exception if the reference is indirect and do so only once per retry sequence

**Pull request closed without merging**
