### PR TITLE
Force correct overload selection to fix compatibility with Intel C++

### PR DESCRIPTION
**Pull request by alexmnazarenko**
Hi. We've managed to build a working version of Ice with intel compiler (Composer XE 2015, Win x64). It works with our (quite complex) app, so hopefully build is correct.

However, it required patch to Ice code which took a while to figure out. Everything just froze on connection establishment. Patch seems to be correct and harmless, so we suggest it to developers to apply in some later version to save trouble to other desperate Intel C++ users.

The problem is in subtle difference in overload selection. In a code:

```C++
#include <iostream>

struct T {}; 
struct PtrT { PtrT(T*) {} };

void f(bool&) { std::cout << "FAIL - bool" << std::endl; }
void f(PtrT) { std::cout << "OK - PtrT" << std::endl; }

int main() {
  f(new T);
}
```

Intel selects "bool&" overload without a warning. Ice source contains few overloads of this type (e.g. IceInternal::OutgoingConnectionFactory::create, Ice::Handle is similar to PtrT in example). The result is awful - pointer to callback gets casted to bool, callback is lost, application freezes.

Hopefully, we got all such places.

### CODE REVIEW

**Comment by bentoi** [comment]
Hi Alex,

Thanks for this pull request! 

After checking out the changes, I don't think the workarounds for OutgoingConnectionFactory::create and RoutableReference::createConnection are still necessary since there are no more overloads for these 2 methods. 

Can you try without the workarounds and confirm that the only change which is still necessary is the one for the LocatorInfo::getEnpdoints overload? Thanks!

Cheers,
Benoit.

**Comment by alexmnazarenko** [comment]
Hi Benoit,

Sorry for not recheking it for 3.6 on my own. We don't use 3.6b yet, so I built 3.5.1 originally. 

Yes, it's enough to fix only LocatorInfo::getEndpoints calls. Do I need to make a different pull request?

ps Hope 3.6 gets released soon. New 'InvocationTimeout' option would very helpful for us )

WBR, 
Alex

**Comment by pepone** [comment]
Hi Alex
3.6.0 was released a few days ago, see https://zeroc.com/forums/announcements/6468-ice-3-6-0-ice-touch-3-6-0-released.html

**Comment by alexmnazarenko** [comment]
Thats some good news!

Already created an issue in our bugtracker to upgrade to it ))

**Comment by bentoi** [comment]
Hi Alex
The best is to submit a new pull request with only the required change. Can you also submit the pull request against the 3.6 branch to ensure this fix gets included in the next 3.6 minor release?
Thanks,
Benoit.

**Comment by alexmnazarenko** [comment]
Aha, updated my commit.

Now its only one line ) Thats some serious change there.

**Comment by bentoi** [comment]
Thanks!

**Comment by alexmnazarenko** [comment]
You've accepted only to 3.6 branch to merge later? Correct?

**Comment by bentoi** [comment]
Correct, we'll merge 3.6 fixes to master at some point.

**Pull request closed without merging**
