### PR TITLE
Sslcerts

### PR DESCRIPTION
**Pull request by pepone**
@externl any idea why this still works on macOS

https://github.com/zeroc-ice/ice/blob/85e4eb59582c45091fdebbbbcb3b2d88f7e1a674/cpp/test/IceSSL/configuration/AllTests.cpp#L3695

I will expect this test to fails as the SUBJECTKEYID has not been updated to match the new certificates.

Maybe the cleanup is not working, and certs are not removed after testing?

### CODE REVIEW

**Comment by externl** [comment]
Pretty sure I updated those.

**Comment by pepone** [comment]
> Pretty sure I updated those.

Maybe was an issue with the merge can you check again

**Comment by externl** [comment]
Hmm.. weird, it indeed looks not changed, but the test doesn't fail.

**Comment by pepone** [comment]
> Hmm.. weird, it indeed looks not changed, but the test doesn't fail.
> 
> EDIT: nvm, it does fail.

can you fix macOS, I fixed Windows SChannel part above

https://github.com/zeroc-ice/ice/blob/85e4eb59582c45091fdebbbbcb3b2d88f7e1a674/cpp/test/IceSSL/configuration/AllTests.cpp#L3538

**Comment by externl** [comment]
Done.

**Pull request merged**
