### PR TITLE
Remove connector

### PR DESCRIPTION
**Pull request by pepone**
This PR removes the IConnector interface, Endpoints will always use the first DNS address

### CODE REVIEW

**Comment by bentoi** [comment]
I just had a quick look for now... I think we might want to put more thoughts into this first.

I believe that with this change connection re-use is just based on endpoint comparison to lookup existing connections. That's not good since two different TCP endpoints might resolve to the same IP address and we'd like these two endpoints to re-use the same connection. But if we still want connection re-use to be based on IP addresses, how do we implement this if we get rid of the connector abstraction? I discussed this on the Transport API page... one possibility is to get rid of the outgoing/incoming connection factory classes and instead have each transport implementation implement these factories -- this allow the transport factory code to implement a connection re-use strategy specific to the transport. 

So rather than have general purpose factories implemented by Ice (Incoming/Outgoing connection factories) that use transport specific connector/acceptor abstractions, we get rid of these abstractions and the transport provides the factory implementation (eventually overriding an abstract class provided by the Ice core).

Also, if I understand it correctly, if the connection fails on the first address returned by the DNS lookup, we don't try other addresses? I think we should try other addresses if we fail to establish the connection on the first address.

**Comment by pepone** [comment]
>Also, if I understand it correctly, if the connection fails on the first address returned by the DNS lookup, we don't try other addresses? I think we should try other addresses if we fail to establish the connection on the first address.

So are you suggesting we should try other addresses if we get a retryable exception while establishing the connection, but then not consider these addresses as separate replicas for remote exception retries?

**Comment by pepone** [comment]
>. one possibility is to get rid of the outgoing/incoming connection factory classes and instead have each transport implementation implement these factories -- this allow the transport factory code to implement a connection re-use strategy specific to the transport.

Can we implement this in the connection specializations? IPConnection can check if the Endpoint is an IPEndpoint and if any of the resolved addresses matches the RemoteEndpoint

**Comment by bentoi** [comment]
> So are you suggesting we should try other addresses if we get a retryable exception while establishing the connection, but then not consider these addresses as separate replicas for remote exception retries?

I didn't put much thoughts into it but I'd think this shouldn't be part of the Ice retry loop, it's something internal to each transport implementation, i.e.: the factory create method would take care of the retry on other addresses (in the order returned by the DNS lookup).

> Can we implement this in the connection specializations? IPConnection can check if the Endpoint is an IPEndpoint and if any of the resolved addresses matches the RemoteEndpoint

The goal is to be able to lookup connections by IP address so I don't see how this would work if you need the connection to be able to compare it with the endpoint IP addresses. Or this would require to loop over all the outgoing connections to search for a re-useable connection instead of a dictionary lookup? Even if it's less important for outgoing connections, this wouldn't be very scalable.

**Pull request closed without merging**
