### PR TITLE
Update Python Packages build instructions

### LINKED ISSUE #2628: Building Python Packages with build
It would be nice to provide macos-with-homebrew instructions.

It's not immediately clear to which platform the current instructions apply.

### PR DESCRIPTION
**Pull request by pepone**
Fixes #2628

### CODE REVIEW

**Review by externl — APPROVED** [review]
Looks good. Should we prefer `python3` over `python`?

**Review by bernardnormier — APPROVED** [review]
Unless somehow the instructions are truly identical for Windows, Linux and macOS, I would prefer platform-specific instructions.

For example, I believe python is `python3` on Linux/macOS, where if you install Python for Windows from https://www.python.org/downloads/windows/, it's called `python`.

**Comment by externl** [comment]
> Unless somehow the instructions are truly identical for Windows, Linux and macOS, I would prefer platform-specific instructions.
> 
> For example, I believe python is `python3` on Linux/macOS, whereas if you install Python for Windows from https://www.python.org/downloads/windows/, it's called `python`.

I'm pretty sure if you pick any other Python project on GitHub it will not have platform specific instructions like this.

**Comment by pepone** [comment]
> Unless somehow the instructions are truly identical for Windows, Linux and macOS, I would prefer platform-specific instructions.

That is one difference for Windows, after reviewing it, I think `source .venv/bin/activate` is not valid for Windows either.

**Pull request merged**
