### PR TITLE
Add java coverage workflow

### PR DESCRIPTION
**Pull request by externl**
You can see the output [here](https://code.zeroc.com/ice/java/main/coverage/index.html)

### CODE REVIEW

**Review by pepone — APPROVED** [review]
Looks good. Can we filter out IceGridGUI?

**Comment by bernardnormier** [comment]
Did you use a very old main for this coverage report?

It shows:

InputStream(Communicator, ByteBuffer) |   | 0% |   | n/a | 1 | 1 | 4 | 4 | 1 | 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
InputStream(Communicator, EncodingVersion, ByteBuffer) |   | 0% |   | n/a | 1 | 1 | 2 | 2 | 1 | 1

[InputStream(Communicator, ByteBuffer)](https://code.zeroc.com/ice/java/main/coverage/com.zeroc.Ice/InputStream.java.html#L34)	13	0%		n/a	1	1	4	4	1	1
[InputStream(Communicator, EncodingVersion, ByteBuffer)](https://code.zeroc.com/ice/java/main/coverage/com.zeroc.Ice/InputStream.java.html#L60)	10	0%		n/a	1	1	2	2	1	1

which were removed months ago.

**Comment by bernardnormier** [comment]
It would be good to filter out the generated code as well.

**Comment by externl** [comment]
I'll update in a follow-up PR to remove the generated code and remove the IceGrid GUI

**Pull request merged**
