### PR TITLE
Fix compilation errors caused by parameters not declared in this scope

### PR DESCRIPTION
**Pull request by Harvey-Liu**

### CODE REVIEW

**Comment by pepone** [comment]
Hi @Harvey-Liu thanks for the contribution can you review the contributor agreement posted above by zcabot, we will merge this once you send us the signed agreement.

Cheers,
Jose

**Comment by Harvey-Liu** [comment]
Hi @pepone , I have sent the signed agreement to the mailbox

**Comment by bernardnormier** [comment]
> Hi @pepone , I have sent the signed agreement to the mailbox

Unfortunately we did not receive it. Can you please email it again to contributing@zeroc.com?

Thanks,
Bernard

**Comment by Harvey-Liu** [comment]
> > Hi @pepone , I have sent the signed agreement to the mailbox
> 
> Unfortunately we did not receive it. Can you please email it again to [contributing@zeroc.com](mailto:contributing@zeroc.com)?
> 
> Thanks,
> Bernard

Ok, I have sent it again, the main body of the email is Harvey-Liu ZCA

Thanks,
Harvey

**Comment by externl** [comment]
I cherry-picked this into master at 4973122e6b54de2143f445a4ccbeff6243ec5e54

**Pull request merged**
