### PR TITLE
Fixes #369 

### LINKED ISSUE #369: Remove outdated nonmutating comment
See https://github.com/zeroc-ice/ice/blob/3.7/cpp/src/Ice/Object.cpp#L329
```
// Note that expected == Nonmutating and received == Idempotent is not ok:
// the server may still use the deprecated nonmutating keyword to detect updates
// and the client should not break this (deprecated) feature.
```
The `nonmutating` keyword was removed in Ice 3.3 and since then the expected operation mode on the server side cannot be `Nonmutating`. We should remove this comment in C++, check other language mappings, and add an assert `expected != Nonmutating`.

### PR DESCRIPTION
**Pull request by kvaghel1**
Outdated comments removed and assert statement added.

### CODE REVIEW

**Comment by pepone** [comment]
There is similar outdated comment in 
https://github.com/zeroc-ice/ice/blob/661ea02daeeabb2d2e809c7d7f73b63095f85622/objective-c/src/Ice/Object.mm#L252-L260

**Comment by kvaghel1** [comment]
Changes updated for objective-c file.

**Comment by bernardnormier** [comment]
The original C++ code is:

```
    if(expected != received)
    {
        if(expected == ICE_ENUM(OperationMode, Idempotent) && received == ICE_ENUM(OperationMode, Nonmutating))
        {
            //
            // Fine: typically an old client still using the deprecated nonmutating keyword
            //

            // --- start of old incorrect comment ---
            // Note that expected == Nonmutating and received == Idempotent is not ok:
            // the server may still use the deprecated nonmutating keyword to detect updates
            // and the client should not break this (deprecated) feature.
            // --- end of old incorrect comment
        }
        else
        {
            ...
            throw Ice::MarshalException(__FILE__, __LINE__, reason.str());
        }
    }

```
There is no point in asserting in `if` that expected is not Nonmutating, since we already know it's idempotent. I suggest something more like:

```
    assert(expected != ICE_ENUM(OperationMode, Nonmutating)); // We never expect Nonmutating
    if(expected != received)
    {
        if(expected == ICE_ENUM(OperationMode, Idempotent) && received == ICE_ENUM(OperationMode, Nonmutating))
        {
            //
            // Fine: typically an old client still using the deprecated nonmutating keyword
            //
        }
        else
        {
            ...
            throw Ice::MarshalException(__FILE__, __LINE__, reason.str());
        }
    }
```

Note the syntax for the enumerator: ICE_ENUM(...), which is required for code that compiles with both the C++98 and C++11 mappings. And in ObjC, the enumerator is `ICENonmutating`.

**Comment by bernardnormier** [comment]
I've just fixed this bug as suggested in the comment above.

**Pull request closed without merging**
