### PR TITLE
Remove Useless Language-Specific Metadata

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
It's clear that many of our test Slice files were copy/pasted from other languages.
This PR removes metadata that is useless, and probably just leftover from the copy/pastes.

Ex: Using `["cpp:const"]` in the Swift tests...

This is useless right? I guess CI will tell me.

### CODE REVIEW

**Review by bernardnormier — APPROVED** [review]
Do we have a test that verifies metadata from other languages are ignored?

**Comment by bernardnormier** [comment]
> Ex: Using `["cpp:const"]` in the Swift tests...

cpp:const is useless even in C++. We keep it only to make it easier to upgrade your servant to Ice 3.8.

**Review by pepone — APPROVED** [review]

**Comment by InsertCreativityHere** [comment]
> cpp:const is useless even in C++. We keep it only to make it easier to upgrade your servant to Ice 3.8.

Good to know, I'll remove it from all of our files.

**Comment by InsertCreativityHere** [comment]
> Do we have a test that verifies metadata from other languages are ignored?

I didn't see one at least. But I'll add a test case to the `WarningInvalidMetadata` for this.

**Comment by pepone** [comment]
> Do we have a test that verifies metadata from other languages are ignored?

I'm not sure we need that kind of test, compilers query metadata using prefixes, what will we test here?

**Comment by InsertCreativityHere** [comment]
> I'm not sure we need that kind of test, compilers query metadata using prefixes, what will we test here?

I was going to add this line to one of the errorDetection:
`["bad", "cpp:bad", "java:bad"] // We only validate metadata when it has an applicable language prefix`
and make sure that we **don't** issue a warning for `java:bad` (since it's only run with `slice2cpp`.

**Comment by InsertCreativityHere** [comment]
@pepone

I opened a PR which adds my test idea.
It's pretty small, so if you think it's useless to do, feel free to say so! : v)

**Pull request merged**
