### PR TITLE
Connection info refactoring

### PR DESCRIPTION
**Pull request by pepone**
This PR removes the underlying member of ConnectionInfo classes and arrange the classes in a hierarchy, similar to what I previously did for EndpointInfo classes.

Removed the Verified member of SslConnectionInfo, as we no longer allow unverified connections with recent changes to VerifyPeer=0 behavior.

### CODE REVIEW

**Comment by bernardnormier** [comment]
Do we need all this ConnectionInfo class hierarchy?

For example, I think all the information provided by the base `ConnectionInfo` class could/should be provided directly by `Connection`.

**Comment by pepone** [comment]
- The Endpoint is already public property of the connection, maybe the adapter should be too.
- For incoming is this useful?

One question is what will we use as the return type of GetConnectionInfo if we remove the base class, we can use IpConnectionInfo but this will not work if we later have to add an non Ip transport.

**Comment by bentoi** [comment]
Doesn't Bernard suggest to remove all the info classes not just ConnectionInfo? 

This would require to create specializations of the Connection class such as IPConnection, UdpConnection, TcpConnection to provide the transport specific information provided by the transceiver class... or we expose the transport transceiver classes through the connection.

**Comment by bernardnormier** [comment]
> This would require to create specializations of the Connection class such as IPConnection, UdpConnection, TcpConnection to provide the transport specific information

Yes, that's what I was thinking about.

**Pull request closed without merging**
