### PR TITLE
Icessl protocols

### PR DESCRIPTION
**Pull request by pepone**
This PR removes support for setting SSL protocols using IceSSL properties, `IceSSL.Protocols`, `IceSSL.ProtocolVersionMax`, and `IceSSL.ProtocolVersionMin`.

The SSL transport would use the system defaults, there is usually no need to change this. For advanced use cases, you can change the system defaults or use the IceSSL native API.

### CODE REVIEW

**Comment by externl** [comment]
One downside with this change is that the user can no longer change the protocols for the Ice services. Is this an issue?

**Comment by pepone** [comment]
> One downside with this change is that the user can no longer change the protocols for the Ice services. Is this an issue?

We can keep it and support only 1.2 and 1.3, there is no reason to support anything older. Would you prefer that? I don't see a reason to allow enabling older versions, which might be disabled by platform and not work.

**Comment by externl** [comment]
Good point, I forgot this setting is not useful with newer versions of TLS.

**Review by externl — APPROVED** [review]
Looks good. Should we explicitly enable only TLS 1.2 and 1.3 or just rely on what the defaults are set to?

**Review by bernardnormier — APPROVED** [review]
I agree: this is an advanced feature, and if you want it, you should use the programmatic API we offer in 3.8.

**Pull request merged**
